#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         go-perl
version:      0.03
version_from: go-perl.pod
installdirs:  site
requires:
    Data::Dumper:                  0
    Data::Stag:                    0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
